### ISSUE TITLE
virtually no overlapping annotations?

### ISSUE THREAD

**Issue by mdingemanse** [saulalbert/CABNC#7]
Thanks for making available this resource Saul and others! I'm expecting we're doing something wrong in our processing pipeline, but our inspection of CABNC seems to indicate there are virtually no annotations that overlap in timing. A quick plot of FTO (in the sense of De Ruiter et al. 2006) by turn duration looks like this:

![qc-english1-cabnc-FTO-by-duration](https://user-images.githubusercontent.com/9883915/227509483-83424be0-a9e7-49fd-a256-20d1c1a25d2e.png)

In contrast, this is what Talkbank CallFriend looks like (plot from here: https://aclanthology.org/2022.lrec-1.126/ )

![image](https://user-images.githubusercontent.com/9883915/227510292-0c41fc5d-c0fc-4064-9730-4a74ced457c1.png)

**Comment by saulalbert** [comment]
Hi Mark,

Indeed - you'll find no overlapped annotations here because the timing data for CABNC is not in any way precise: it was  created using automated forced alignment - then transposed into CHAT/TalkBank XML as a 'first pass' for hand transcription. 

The original intention was for the CABNC to be a useful/searchable starting point for CA researchers, not for computational linguistics - at least not until it is sufficiently hand-annotated (by CA researchers, I was hoping) for people to use it for quantitative analysis.

Partly due to problems with collaborative annotation interfaces (CLAN not being ideal), partly due to lack of time and other data becoming available that is probably a better fit for this kind of project, I haven't managed to get the idea of crowdsourcing annotation going with the CABNC, though I still think it would be a good idea in principle!

Best,

Saul

**Comment by mdingemanse** [comment]
Thanks for clarifying Saul and no worries! As you note, there is indeed plenty of other available data for English.
